trigger:
  branches:
    include:
      - deploy

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Maven@4
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean package'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      failTaskOnFailedTests: true

  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'DevOps_APPs'
      appName: 'azspring'
      package: '$(System.DefaultWorkingDirectory)/**/target/*.jar'