trigger:
  branches:
    include:
      - docker

variables:
  imageName: 'azspring-app'
  containerRegistry: 'myacrpucpr.azurecr.io'
  dockerTag: '$(Build.BuildId)'

stages:
  - stage: Test
    displayName: "Test Stage"
    jobs:
      - job: Test
        displayName: "Test Job"
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self

          - script: |
              echo "Verificando Docker e Maven..."
              docker --version
              mvn -version
            displayName: 'Check Docker and Maven'

          - script: |
              echo "Executando testes com Testcontainers..."
              mvn verify
            displayName: 'Run Unit and Integration Tests'

          - task: PublishTestResults@2
            inputs:
              testResultsFormat: 'JUnit'
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              failTaskOnFailedTests: true