trigger:
  branches:
    include:
      - stages

stages:
  - stage: Build
    displayName: "Build Stage"
    jobs:
      - job: Build
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: Maven@4
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'clean package'

  - stage: Test
    displayName: "Test Stage"
    dependsOn: Build
    jobs:
      - job: Test
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: Maven@4
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'test'

          - task: PublishTestResults@2
            inputs:
              testResultsFormat: 'JUnit'
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              failTaskOnFailedTests: true

  - stage: Deploy
    displayName: "Deploy Stage"
    dependsOn: Test
    condition: succeeded()
    jobs:
      - job: Deploy
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'DevOps_APPs'
              appName: 'azspring'
              package: '$(System.DefaultWorkingDirectory)/**/target/*.jar'